### ISSUE TITLE
MySQL Server has Gone away

### ISSUE THREAD

**Issue by EndenDragon** [bbangert/beaker#126]
I have been getting these~
`OperationalError: (_mysql_exceptions.OperationalError) (2006, 'MySQL server has gone away')`

Is there a flag to set when to recycle mysql connections? I know that you can do this with Flask SQLAlchemy with `app.config['SQLALCHEMY_POOL_RECYCLE']`.

**Comment by amol-** [comment]
How do you create the database cache manager? The namespace manager for database supports a `sa_opts` parameter where you can pass the `pool_recycle` option

**Comment by EndenDragon** [comment]
This is how I created the cache manager
https://github.com/EndenDragon/Titan/blob/master/titanembeds/utils.py#L17

I'm not sure how to initialize the namespace manager.

**Comment by amol-** [comment]
Here is a short snippet to showcase what you are looking for:

```
from beaker.cache import CacheManager
from beaker.util import parse_cache_config_options
cache_opts = {
    'cache.type': 'ext:database',
    'cache.data_dir': 'tmp/cachedata',
    'cache.lock_dir': 'tmp/cachelock',
    'cache.url': 'sqlite:///:memory:',
    'cache.sa.pool_recycle': 250
}
cachemanager = CacheManager(**parse_cache_config_options(cache_opts))
cache = cachemanager.get_cache('test')
engine = cache.namespace.cache.metadata.bind
print engine.pool._recycle
```

**Comment by EndenDragon** [comment]
Awesome!!
`cache.sa.pool_recycle` config option is exactly what I'm looking for, thanks!!
