### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by schlenk** [bbangert/beaker#132]
Could you please cut a new release tag/version to appear on pypi?

Mostly to get rid of the unmaintained pycrypto dependency.

**Comment by amol-** [comment]
Yes, I already planned a release as soon as I finish the experimental support for builtin mongodb storage and locking which is undergoing in `ext-managers` branch. That would act as the foundation for rewrite of available namespace managers and I want to include it in the upcoming release to gather feedbacks and bugs.

**Comment by amol-** [comment]
https://pypi.python.org/pypi/Beaker/1.9.0
