### ISSUE TITLE
Encrypted cookies don't work in Python 3.2

### ISSUE THREAD

**Issue by kiwidrew** [bbangert/beaker#21]
It appears that none of the beaker.crypto code is ready for Python 3.  In particular, pbkdf2.py does a bunch of isinstance() checks which enforce that the encryption keys are 'str' objects, and calls encode() on them if not.  This is of course precisely backwards when working with str and bytes in Python 3.

I've tried making a few patches to the code, but this only serves to reveal additional issues, and I don't have the time to prepare a complete patch for now.

In the meantime, please update the docs to indicate that encrypted cookies (that is, cookie-only sessions) are not supported when running under Python 3.

**Comment by FedericoCeratto** [comment]
@amol-  added patch to support Python3 #75 
The code is a bit tricky, I'd recommend improving the unit testing around the module.

**Comment by amol-** [comment]
backported pbkdf2 and added four pbkdf2 related tests to ensure behaviour is the same as before.
It seems that it is now correctly working on Python3.4 which is now included in travis:

https://travis-ci.org/bbangert/beaker

**Comment by amol-** [comment]
Beaker is now natively python3 compatible and will be released as 1.7.0dev as a prerelease

See https://travis-ci.org/bbangert/beaker/builds/52155288

**Comment by FedericoCeratto** [comment]
:cake:
