### ISSUE TITLE
Can't connect to several nodes and/or in cluster mode

### ISSUE THREAD

**Issue by Millefeuille42** [bbangert/beaker#235]
I'm using Beaker via pyramid_beaker for Tracim, but I'm encountering issues connecting to Redis clusters. Specifically, I'm getting a `redis.exceptions.ResponseError: MOVED` error. This problem can be circumvented by using the `RedisCluster` class introduced in `redis-py 4.1.0`. Additionally, connecting to multiple nodes simultaneously isn't supported.

To address this, a possible solution would be to implement an `ext:redis_cluster` driver in Beaker that allows for multiple nodes in the URL parameter, such as `"redis://node-1:6379/0,redis://node-2:6379/0"`.

- Could it be that I'm misunderstanding Beaker's cluster support capabilities?
- Do you have any information about a redis-cluster ready session backend ?
- Alternatively, is it feasible for us to develop the `ext:redis_cluster` driver and submit it to Beaker via a pull request?

**Comment by amol-** [comment]
Fixed by #236
