### ISSUE TITLE
Buggy date calculation in ._delete_cookie

### ISSUE THREAD

**Issue by mikeorr** [bbangert/beaker#6]
`beaker.session.Session._delete_cookie()` contains a buggy date calculation.

```
expires = datetime.utcnow().replace(year=2003)
```

On February 29th of a leap year this raises:

```
ValueError: day is out of range for month
```

The apparent goal is to set a date in the past. Can't it just use a fixed date like '2003-01-01'?

**Comment by dkavanagh** [comment]
Linking to fix: https://github.com/bbangert/beaker/commit/b5afb4d8f746b98555274fecc69f4e21d382a081
