### ISSUE TITLE
Cache decorators are overriding docstring and function name

### ISSUE THREAD

**Issue by ardeois** [bbangert/beaker#64]
When using an decorator for caching, the cached function loose it's docstring and its name becomes 'cached'

It's easy to fix that by using '@wraps' decorator :
https://docs.python.org/2/library/functools.html#functools.wraps

**Comment by amol-** [comment]
The issue was already fixed by another pull request, merged test unit from this one in https://github.com/bbangert/beaker/commit/f9db2638b79e2b7a08b0132a6bd4ed35193af742
