### ISSUE TITLE
session information not carried across requests

### ISSUE THREAD

**Issue by expntly** [bbangert/beaker#72]
The setup is a traditional web client (angularjs) making requests to a web server (python 2.6.9, gunicorn 19.0.0, beaker 1.6.4).

app handling code looks pretty much like so:

```python
from beaker.middleware import SessionMiddleware
session_opts = {
  "session.type": "cookie",
  "session.validate_key": "some secret",
  "session.cookie_expires": 3600*24*90,
  "session.auto": True,
}
app_handler = ...
application = SessionMiddleware(app_handler, session_opts)
```

The web client makes one HTTP GET and two HTTP POST requests **sequentially** against the web server.  The problem is that the last request doesn't seem to carry the session info that the first request added to the session.  Here's what I see in the server logs:

* GET / : sets some session info via session["info"] = "..."
* POST /foo:
  * beaker.session.id cookie is set (just a long b64 hash)
  * session["info"] has my information, as expected
* POST /bar:
  * beaker.session.id cookie is set and seems to have a different value than the hash just before
  * session does not have "info" key, the only thing it's got is an "_id" entry.

So somehow the session info is cleared after the "POST /foo", which makes no sense to me.  Am I missing something?  Also, is beaker.session.id supposed to change all the time?  I seem to always see a different value.

Thanks!

**Comment by vmbb** [comment]
I'm seeing the same behavior but only on Ubuntu 15.04 - on my Mac it works as advertised - the session id doesn't change and data put in the session stays there. On ubuntu, the session is new on every request. I've tried with memory, file, and cookies seeing if it made any difference, but it does not.

**Comment by jeremyherbert** [comment]
I'm also seeing this on Ubuntu 14.04 via gunicorn with flask if I use the "memory" backend. Also with a GET, POST, POST. "file" appears to work fine.

The weird thing is, if I refresh the last POST request several times (maybe 3 or 4), it suddenly works.

**Comment by amol-** [comment]
Can you provide any additional detail? It's really hard to replicate the issue without any other information.

Which browser are you experiencing the issue with?
Is the browser still sending you back the cookie with the session disappears?
How does the Cookie look like? (Expiration, Path etc...)
How does your code that reads/sets session look like?
What kind of data are you storing in the session? How big is it?

I tested it on a newly quickstarted TurboGears2 app with Chrome, Safari and Firefox and all of them were properly incrementing a value and keeping around the session

**Comment by jeremyherbert** [comment]
Hi again,

Sorry, I know it is annoying to get a bug report like this, but I was too busy to post something yesterday :)

Here is my test case, run with `gunicorn -w 4 -b 127.0.0.1:8001 btest:app`:

```
import os
from flask import Flask, request, session, request
from flask.sessions import SessionInterface
from beaker.middleware import SessionMiddleware

class BeakerSessionInterface(SessionInterface):
    def open_session(self, app, request):
        session = request.environ['beaker.session']
        return session

    def save_session(self, app, session, response):
        session.save()

# create a session key
import base64
if not os.path.exists("/tmp/session.key") or not os.path.exists("/tmp/session.secret"):
    with open('/dev/urandom', 'rb') as f:
        session_secret = base64.b32encode(f.read(100)).decode()
        session_key = base64.b32encode(f.read(100)).decode()

    with open("/tmp/session.secret", 'w') as f:
        f.write(session_secret)
    with open("/tmp/session.key", 'w') as f:
        f.write(session_key)
else:
    with open("/tmp/session.secret") as f:
        session_secret = f.read()
    with open("/tmp/session.key") as f:
        session_key = f.read()

session_opts = {
    'session.lock_dir': '/tmp',
    'session.data_dir': '/tmp',
    'session.type': 'memory',
    'session.cookie_expires': int(60*5.5),
    'session.secret': session_secret,
    'session.key': session_key,
    'session.auto': True
}


app = Flask(__name__, template_folder='templates')
app.debug = True
app.wsgi_app = SessionMiddleware(app.wsgi_app, session_opts)
app.session_interface = BeakerSessionInterface()

@app.after_request
def after_request(response):
    response.headers.add('Cache-Control', 'no-cache, no-store, must-revalidate')
    response.headers.add('Pragma', 'no-cache')
    response.headers.add('Expires', '0')
    return response

@app.route("/", methods=['GET', 'POST'])
def index():
    session['info'] = ''
    if request.method == 'GET':
        return '<!html><form action="/" method="POST"><input type="submit" value="go!"></form>'
    if request.method == 'POST':
        session['info'] = 'something'
        return '<!html><form action="/submit" method="POST"><input type="submit" value="go again!"></form>'

@app.route("/submit", methods=['POST'])
def submit():
    return str(session)

if __name__ == '__main__':
    app.debug = True
    app.run()
```

If I go through this process, my session printout looks like this:

```
{'_creation_time': 1439936314.5529828, 'info': '', '_accessed_time': 1439936330.7012515}
```

refresh a few times and it does this:

```
{'_accessed_time': 1439936514.5527587, '_creation_time': 1439936514.5527587}
```

it cycles between these two on refresh.

If I go back to `/` and try again, sometimes it just works:
```
{'_accessed_time': 1439936559.4425476, 'info': 'something', '_creation_time': 1439936514.5527587}
```

And sometimes if it needs a few refreshes to go through.

My cookie name and value don't change in python, nor do they change in my browser which is Chrome 44.0.2403.155 (64-bit) on OSX. But the app is not running on my local OSX machine.

my `pip freeze`:
```
Beaker==1.7.0
cairocffi==0.7.2
cffi==1.1.2
Flask==0.10.1
gunicorn==19.3.0
itsdangerous==0.24
Jinja2==2.8
MarkupSafe==0.23
ply==3.4
pycparser==2.10
pyparsing==2.0.3
requests==2.7.0
virtualenv==13.1.0
Werkzeug==0.10.4
```

`uname -r` gives `3.13.0`

`/proc/version` gives `Linux version 3.13.0 (gcc version 4.4.4) #BrandZ virtual linux SMP 00:00:00 00/00/00`

My `python --version` gives `Python 3.4.0`.

Hope this helps.

**Comment by jeremyherbert** [comment]
And... I just realised what it is. If you run gunicorn with only 1 worker, the problem goes away. Clearly in the memory backend, the sessions are not shared across workers on the same host. Is this intentional? They are indeed running as separate processes.

**Comment by bbangert** [comment]
The memory back-end is process-specific, as its the Python process memory that is used. That is intentional, as the memory back-end is mainly intended for testing purposes.

**Comment by jeremyherbert** [comment]
Ok, that makes perfect sense. Perhaps this could be added to the documentation, under the configuration settings area ?

**Comment by amol-** [comment]
Added a warning in sessions section at https://github.com/bbangert/beaker/commit/96d678d786844d3d18f293a79acc9ee29fbd983e -> http://beaker.readthedocs.org/en/latest/sessions.html#saving

@bbangert can you add me to readthedocs? It would make easier to tackle issues in doc builds.

**Comment by bbangert** [comment]
@amol- sure, what username?

**Comment by amol-** [comment]
@bbangert amol :)

**Comment by bbangert** [comment]
Ok, you've been added!

**Comment by amanaman92** [comment]
@bbangert @jeremyherbert @vmbb 
Hi,
I'm also facing the same issue. Can you please provide me appropriate solution for this issue. 

I have two requests: <Request 'http://localhost:8000/onelogin_auth/?sso' [GET]> and <Request 'http://0.0.0.0:8000/onelogin_auth/?acs' [POST]>. I want them to have same session id but beaker is assigning different session id to POST.

My session parameters are: session_opts = {
    'session.type': 'cookie',
    'session.data_dir': './data',
    'session.cookie_expires': 3600,
    'session.validate_key': 'some key',
    'session.encript_key': 'some key',
    'session.auto': True
}
I'm using Linux. I guess it was working fine on MacOS.
I want to set parameters received from POST into GET session. This would have been easy if they were assigned the same session id.

Thank You
