### ISSUE TITLE
Allow using beaker with cryptography package instead of pycrypto

### ISSUE THREAD

**Issue by schlenk** [bbangert/beaker#73]
It would be nice if the pyca/cryptography package could be used with beaker instead of the pycrypto etc. files.
https://github.com/pyca/cryptography

**Comment by amol-** [comment]
Could you please point out what would be the main advantages of using pyca/cryptography in place of pycrypto? I never used the pyca/cryptography package so I'm not aware of its advantages and disadvantages when related to pycrypto.

**Comment by schlenk** [comment]
Oh, mostly it is just cutting down the amount of crypto library dependencies in use.

I have some project also using Twisted + pyopenssl which is based on pyca/cryptography these days, and am reluctant to add another crypto library without need.

Why cryptography and all that is mostly told by the cryptography docs and the blog post  https://alexgaynor.net/2014/feb/12/why-crypto/
