### ISSUE TITLE
Please don't install tests in the site-packages/ folder

### ISSUE THREAD

**Issue by felixonmars** [bbangert/beaker#74]
Since 1.6.5 the installation script is installing the "tests" folder into site-packages/ folder, which can easily conflict with other packages. Please either install them in site-packages/beaker/tests or rather just don't install them, as all the top level test_* files were not installed already.

Related logs:
```
creating /build/python-beaker/pkg/python2-beaker/usr/lib/python2.7/site-packages/tests
creating /build/python-beaker/pkg/python2-beaker/usr/lib/python2.7/site-packages/tests/test_namespacing_files
copying build/lib/tests/test_namespacing_files/__init__.py -> /build/python-beaker/pkg/python2-beaker/usr/lib/python2.7/site-packages/tests/test_namespacing_files
copying build/lib/tests/test_namespacing_files/namespace_get.py -> /build/python-beaker/pkg/python2-beaker/usr/lib/python2.7/site-packages/tests/test_namespacing_files
copying build/lib/tests/test_namespacing_files/namespace_go.py -> /build/python-beaker/pkg/python2-beaker/usr/lib/python2.7/site-packages/tests/test_namespacing_files
```

**Comment by amol-** [comment]
oops, didn't notice this. 
I took for granted that the setup.py was fine and it excluded all tests, package should now be fine.

I rolled out a post-release to fix this 1.6.5.post1
