### ISSUE TITLE
Bottle() and sub-apps w/ beaker

### ISSUE THREAD

**Issue by Nitesedge** [bbangert/beaker#79]
I am trying to use bottle's object functionality to be able to import subapps and then mount them into the global default application. However, when I try to include beaker for session management I run into issues:

```

from bottle import Bottle
from beaker.middleware import SessionMiddleware

session_opts = {
    'session.type': 'file',
    'session.cookie_expires': 300,
    'session.data_dir': './data',
    'session.auto': True
}

app = Bottle()
app = SessionMiddleware(app, session_opts)

#Import Subapp
from subapp import subapp #Assumes subapp.py and associated import
app.mount('/subapp', subapp) #Assumes subapp.py and associated import

@app.route('/')
def hello():
    return 'Hello World'

app.run()
```
Error:
```
Traceback (most recent call last):
 File "example.py", line 14, in <module>
 @app.route('/')
 AttributeError: 'SessionMiddleware' object has no attribute 'route'
```
Is this behaviour supported by beaker? If so, can you advise what I am doing wrong here?

**Comment by amol-** [comment]
You are wrapping app with the beaker middleare, so app is not a Bottle object anymore.
You should apply the middleware after you configured your app, not before.

See: http://bottlepy.org/docs/dev/recipes.html#keeping-track-of-sessions
