### ISSUE TITLE
Incorrect behavior of bytes_() under Python3.4

### ISSUE THREAD

**Issue by FedericoCeratto** [bbangert/beaker#81]
The second assert fails under Python3.4 because str(b'a') actually returns "b'a'"

```
from beaker._compat import u_, bytes_ 
def test_bytes_conv(): 
    assert bytes_(u'a') == b'a' 
    assert bytes_(b'a') == b'a' 
```

**Comment by amol-** [comment]
right, I already faced the bug when porting it and I thought it was fixed as test_pbkdf2 now pass.
I'll work on it
