### ISSUE TITLE
make all-pdf

### ISSUE THREAD

**Issue by asarch** [bbangert/beaker#82]
# make latex
mkdir -p build/latex build/doctrees
sphinx-build -b latex -d build/doctrees   . build/latex
Running Sphinx v1.3.1
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [latex]: all documents
updating environment: 17 added, 0 changed, 0 removed
reading sources... [100%] sessions                                                                                            
../../CHANGELOG:11: WARNING: Title underline too short.

Release 1.6.5 (2015-02-06)
=========================
../../CHANGELOG:11: WARNING: Title underline too short.

Release 1.6.5 (2015-02-06)
=========================
../../CHANGELOG:356: WARNING: Inline strong start-string without end-string.
../../CHANGELOG:515: WARNING: Inline strong start-string without end-string.
../../CHANGELOG:515: WARNING: Inline strong start-string without end-string.
/home/asarch/beaker/beaker/beaker/docs/modules/pbkdf2.rst:9: WARNING: autodoc: failed to import function u'crypt' from module u'beaker.crypto.pbkdf2'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 392, in import_object
    obj = self.get_attr(obj, part)
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 288, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python2.7/site-packages/sphinx/util/inspect.py", line 115, in safe_getattr
    raise AttributeError(name)
AttributeError: crypt
/home/asarch/beaker/beaker/beaker/docs/modules/pbkdf2.rst:10: WARNING: autodoc: failed to import class u'PBKDF2' from module $'beaker.crypto.pbkdf2'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 392, in import_object
    obj = self.get_attr(obj, part)
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 288, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python2.7/site-packages/sphinx/util/inspect.py", line 115, in safe_getattr
    raise AttributeError(name)
AttributeError: PBKDF2
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/asarch/beaker/beaker/beaker/docs/glossary.rst:: WARNING: document isn't included in any toctree
done
WARNING: "latex_documents" config value references unknown document contents
copying TeX support files...
done
build succeeded, 9 warnings.

Build finished; the LaTeX files are in build/latex.
Run `make all-pdf' or `make all-ps' in that directory to run these through (pdf)latex.

**Comment by amol-** [comment]
AttributeError exceptions got solved in 5c407db775798f99443c3d5eb4959d9335e569ed

This should now result in a correctly compiling documentation
