### ISSUE TITLE
Project URL used on GitHub Project is Invalid

### ISSUE THREAD

**Issue by rsyring** [bbangert/beaker#89]
The GitHub project URL is: 

https://beaker.groovie.org/

which doesn't work.  I'm assuming it's the SSL causing the problem b/c http://beaker.groovie.org/ works.

**Comment by amol-** [comment]
Looks like you are right, @bbangert can you please change it in the github project description? Looks like I cannot. Maybe should be replaced with the readthedocs url as today it's what's widely used?

**Comment by bbangert** [comment]
Sure thing, I have updated it to use the appropriate current SSL RTD link.
