### ISSUE TITLE
beaker/crypto/pbkdf2.py fails to reproduce Django's copyright notice

### ISSUE THREAD

**Issue by alex** [bbangert/beaker#93]
The code in https://github.com/bbangert/beaker/blob/master/beaker/crypto/pbkdf2.py is a direct copy of Django's: https://github.com/django/django/blob/master/django/utils/crypto.py#L108-L191

Per Django's license, the copyright for it must be reproduced.

**Comment by amol-** [comment]
Thanks for pointing out, https://github.com/bbangert/beaker/commit/783a9ad3d93879090b7b55411b3372bf520c0859 should now properly report that the module is based on django one.
